name: languephundrakcom
description: A bare-bone server for my linguistics website.
version: 1.0.0
homepage: https://langue.phundrak.com
author: Lucien Cartier-Tilet <lucien@phundrak.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  js: '^0.6.1+1'

dev_dependencies:
  build_runner: ^1.8.0
  build_web_compilers: ^2.9.0
  pedantic: ^1.9.0
